### ISSUE TITLE
Is there a better syntax highlighting theme?

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-common#122]
"Pretty colors sell"  -- Can we improve both the usability and the attractiveness of our code examples with a different Highlight.js theme? 

@jgeewax has suggested [Solarized Dark](https://github.com/isagalaev/highlight.js/blob/master/src/styles/solarized-dark.css), but please take a look through the full lineup on the [Highlight.js demo](https://highlightjs.org/static/demo/), and enter your suggestion here.

**Comment by stephenplusplus** [comment]
I'm cool with Solarized Dark or Monokai Sublime:

<img width="810" alt="screen shot 2016-04-04 at 7 12 16 pm" src="https://cloud.githubusercontent.com/assets/723048/14267090/4211723a-fa9b-11e5-9fb4-68a098c4fd64.png">

<img width="822" alt="screen shot 2016-04-04 at 7 26 53 pm" src="https://cloud.githubusercontent.com/assets/723048/14267086/3e7b918c-fa9b-11e5-85c9-68dee600aa62.png">

**Comment by jgeewax** [comment]
I think the second one is actually prettier .... not sure which one it is... but :+1: from me.

**Comment by stephenplusplus** [comment]
That one is Monokai Sublime (updated the post to make that more clear)

**Comment by quartzmo** [comment]
I updated the [gcloud-ruby demo](http://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/bigquery) with Monokai Sublime, if anyone wants to check it out. (Note that Highlight.js' Ruby syntax highlighting is pretty lackluster, so another language may be better for comparing themes.)

**Comment by callmehiphop** [comment]
Truthfully I'm not a huge fan of the darker themes. I liked the old (current) theme because the colors compliment the side navigation well and it keeps our palette nice and small. However, I *do* think the current theme could definitely use more colors around the syntax highlighting itself though.

What about something like solarized light and we change the background color to be consistent with the navigation background color?

JS
<img width="732" alt="screen shot 2016-04-05 at 11 41 09 am" src="https://cloud.githubusercontent.com/assets/1707267/14288118/61f43096-fb23-11e5-9d0a-999f3ac8fbc2.png">

Ruby
<img width="625" alt="screen shot 2016-04-05 at 11 41 24 am" src="https://cloud.githubusercontent.com/assets/1707267/14288126/69701ace-fb23-11e5-8a40-16fa130db933.png">

**Comment by stephenplusplus** [comment]
This could be a ridiculous thing to say, but I think there's a lot of reasoning behind the color decisions in the solarized collection (http://ethanschoonover.com/solarized#features), so I don't know if customizing it to suit our site would be hacky. Maybe just the original theme as-is will work, or just a different light theme if the background color is too much of an issue.

**Comment by callmehiphop** [comment]
> This could be a ridiculous thing to say, but I think there's a lot of reasoning behind the color decisions in the solarized collection

Actually I think that's a pretty fair point and I would agree that it *is* a little bit hacky. Something about the dark themes don't look quite right to me, however this isn't something I'm super passionate about, so if the rest of the group wants a dark theme, that's ok with me :smile:

**Comment by jgeewax** [comment]
I'm down with the examples from that screen shot... :)
