### ISSUE TITLE
Possibility of auto generating toc.json for site building

### ISSUE THREAD

**Issue by daspecster** [googleapis/google-cloud-common#132]
Pulling this over here as @jgeewax suggested (https://github.com/GoogleCloudPlatform/gcloud-python/pull/1775#discussion_r62203201).

I'm not sure that the `toc.json` could very easily be generated. Possibly the mapping could be, but the static tutorial/guide files would probably still have to be added.  Unless the locations were standardized?

**Comment by callmehiphop** [comment]
We could probably do away with the guides section of the <kbd>toc.json</kbd>, currently I think we all use the same ones? This would really only present a problem if in the future a language wanted to add a one-off/language specific guide.

Aside from that I think it could be generated.

/cc @quartzmo @blowmage

**Comment by jgeewax** [comment]
Let's also keep in mind that the main work is when we add a new language to the mix. After that, it's all minor changes as we add/remove APIs. If it's not too much work here, might be better to leave alone.

**Comment by blowmage** [comment]
We currently write this file by hand, but we will be automating it soon.

Guides are problematic for many reasons. Currently, there is no way to link to a guide from the code documentation. Code documentation can link to types and methods, but not guides (unless you link to the public URL, which is what we ended up doing). This means that we don't make as much use of the guides as we'd like.

Not sure I'm the right one to ask about this though. I'm still of the opinion that guides should stay local to the language repo, and local to the version you are reading. As the library changes over time, so should the guidance. But this is not the direction that the docs effort has taken. We've pushed for more and more centralization, and more and more generalization. If that continues to be the direction then I see no reason why the version-specific `toc.json` file should have guides at all. We could replace it with a top-level `guides.json` since all versions are sharing the same guides.

**Comment by stephenplusplus** [comment]
> As the library changes over time, so should the guidance. But this is not the direction that the docs effort has taken.

gcloud-node's guides are versioned. @callmehiphop maybe explain how that works?

**Comment by callmehiphop** [comment]
We have a single local markdown file per guide and when we do a release we just "version" it by moving the guides current state to the latest release folder on our gh-pages branch. I could be wrong, but it looks like gcloud-ruby does something similar..? (https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/gh-pages/json/v0.8.2/authentication.md)

**Comment by blowmage** [comment]
Ah, okay, gcloud-ruby does not [add additional content to FAQ guide](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/gh-pages/json/master/toc.json#L16-L18), but gcloud-node does [add more content](https://github.com/GoogleCloudPlatform/gcloud-node/blob/gh-pages/json/master/toc.json#L15-L17). That additional content would be versioned. My mistake.

**Comment by callmehiphop** [comment]
I dig the idea of a <kbd>guides.json</kbd> file, however I'm curious if that would actually satisfy gcloud-python's needs? Only because they're looking for that file to be generated and this solution would still require manually updates - although it would be a much smaller file and updates would probably occur a lot less frequently.

**Comment by dhermes** [comment]
Specific to Python, the existence of a Sphinx-generated index may makes it easier to translate into `toc.json`.

**Comment by daspecster** [comment]
@dhermes do you have any ideas on how to parse the generated index?  I'm probably missing something obvious here but I haven't found a good way to parse the RST through Sphinx or docutils.

**Comment by dhermes** [comment]
I would start [inside][1] the Sphinx tool and figure out [what it's doing][2]. I ran `tox -e docs` and then manually edited `.tox/docs/lib/python2.7/site-packages/sphinx/application.py` to set a breakpoint inside the constructor of `Sphinx`. I recommend doing the same (and setting breakpoints elsewhere) to get a feel for the internal structure. My hope is that there is no need to re-invent the wheel here, Sphinx has done it all.

[1]: https://github.com/sphinx-doc/sphinx/blob/c9296ba467bd1816647e021b14ed6f89c678259c/sphinx/cmdline.py#L244
[2]: https://github.com/sphinx-doc/sphinx/blob/c9296ba467bd1816647e021b14ed6f89c678259c/sphinx/application.py#L279
