### ISSUE TITLE
site: automating deployments

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/google-cloud-common#172]
It recently came to my attention that of all the libraries using the Angular app only 2 automatically deploy changes (see [`deploy-docs.sh`](https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/deploy-docs.sh#L79)). A few days ago I would not have thought this to be a big deal, however with the recent repository name changes for Node and PHP, some of the links within the language dropdown appear to be broken.

Can we have everyone who's using the Angular app add their repo to the deploy script? If there's hesitation to do so, let's discuss that.
# 
#### Has automatic deployments enabled
- [x] Node
- [x] Python
- [x] Ruby
- [ ] PHP

**Comment by quartzmo** [comment]
@callmehiphop @blowmage I'm preparing a PR for gcloud-ruby right now.

**Comment by dwsupplee** [comment]
Would it make sense to have the doc site push happen on tagged releases after we verify all incorporated changes are good across the board?

Deploying the docs on every merge to master makes me a little hesitant, especially after changes like https://github.com/GoogleCloudPlatform/gcloud-common/pull/167 which would have broken the site for us. We were able to get it fixed quickly, yes, but it also means being very vigilant about monitoring every PR and being able to provide feedback before it is merged in order to avoid any issues.

**Comment by callmehiphop** [comment]
@dwsupplee I think that sounds nice, but I'd be a little worried about trying to coordinate releases (getting everyone to checkout the latest and verify changes). I think your previous suggestion of adding unit and/or e2e tests sounds ideal IMO.

@omaray do you think we could prioritize some time to automate testing?
