### ISSUE TITLE
Soft-warn about application default credentials using gcloud credentials

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-common#257]
Due to user issues with quota and API enablement, the auth libraries should issue a soft warning (that can be silenced) when application default credentials uses user credentials from the Cloud SDK. They should not warn if the credentials for the cloud sdk are service account credentials.

```
Your application has authenticated using end user credentials from Google 
Cloud SDK. We recommend that most server applications use service accounts
 instead. If your application continues to use end user credentials from Cloud 
SDK, you might receive a "quota exceeded" or "API not enabled" error. For 
more information about service accounts, see 
https://cloud.google.com/docs/authentication/.
```

Additional context:
https://groups.google.com/a/google.com/forum/#!topic/client-auth-team/DKqrFw6lL1Q
https://buganizer.corp.google.com/issues/64388723
https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/266

Tracking against the following repos:
- [x] https://github.com/google/google-auth-library-nodejs/issues/396
- [x] https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/266
- [x] https://github.com/google/google-auth-library-java/issues/165
- [x] https://github.com/google/google-auth-library-ruby/issues/143
- [ ] https://github.com/google/google-auth-library-php/issues/198
- [x] https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1047
- [ ] https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/2295
- [ ] https://github.com/google/auth-library-swift/issues/8

**Comment by JustinBeckwith** [comment]
FYI @GoogleCloudPlatform/yoshi @danoscarmike @theacodes

**Comment by broady** [comment]
How should this warning be provided and how can it be silenced?

Maybe it's not very unusual, but it would be surprising for me, at least, to have libraries (especially ones deep in the stack) print things to stderr/stdout.

**Comment by JustinBeckwith** [comment]
@theacodes is covering the what/why :)

**Comment by theacodes** [comment]
In Python, we have the standard library [warnings](https://docs.python.org/3/library/warnings.html) module as a means to emit and filter warnings. We use that mechanism in the canonical auth library [here](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/_default.py#L66). Whatever the equivalent is for each language, let's do that. If there is no equivalent, let's discuss if there's any way we can communicate to users that they are standing on a landmine.

**Comment by dazuma** [comment]
For Ruby we've done this sort of thing before, warning of impending deprecations by writing to stderr, and documenting an environment variable that may be set to disable the warning.

**Comment by theacodes** [comment]
@dazuma sounds super reasonable.

**Comment by broady** [comment]
Did anyone consider augmenting quota/other errors with this warning?

That is, if an API wasn't enabled or there's no quota, and the user was using the Cloud SDK, to add that to the existing warning.

[This post by Dave Cheney](https://dave.cheney.net/2015/11/05/lets-talk-about-logging) is more geared towards application-level logging, but there are some good insights here:
* "Nobody reads warnings, because by definition nothing went wrong. Maybe something might go wrong in the future, but that sounds like someone else’s problem."
* "log.Info should simply write that line to the log output. There should not be an option to turn it off as the user should only be told things which are useful for them."

I don't agree with everything in that post, but I think we can do better than libraries posting messages.(except for that mechanism for Python, which seems pretty reasonable)

**Comment by theacodes** [comment]
That's totally fine too, @broady, as long as it's not too onerous to implement. My only concern there is that users won't know they're using a ticking time bomb until it blows up in their face. The benefit of warning ahead of time is that users will always be informed.

**Comment by jadekler** [comment]
My understanding of this problem is that users are using credentials that may not work for them in the future. Is that correct?

If so, I'm reluctant to print warnings.

- As @broady mentioned, warnings are often ignored.
- It is generally not idiomatic in Go for libraries to print to stderr/stdout unless in severely distressing circumstances (panic cases, for example).
- Go's standard logger (log) is not a leveled logger. Therefore, there is no standard way to write warning messages, nor a way to filter or turn off warnings. I do not think "sort of making it leveled" by  using a specialized environment variable and educating users about it is the right way to go, either.

I think that the ideal solution for this would be for a good error from the API side, which lets each library surface this to the user in whatever way is idiomatic in their respective language.

Less ideally, we could also provide documentation specifically targeted at that error, or perhaps we could augment the `err` with information about what might be happening.

That's my 2c - let me know if anything in there is unreasonable.

**Comment by theacodes** [comment]
> Less ideally, we could also provide documentation specifically targeted at that error, or perhaps we could augment the err with information about what might be happening.

That seems to be the most reasonable route for go, so let's do that.

Let me be clear - this approach is to allow users some notification that we discourage the use of these credentials so that we may eventually deprecate them. Please bear in mind that I'm happy for us to be as noisy as possible to convey how problematic these credentials are. It's one of the top reasons why users fail to complete quickstarts.
