### ISSUE TITLE
Move storage conformance tests to this repo

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-common#281]
cc @frankyn @jskeet 

Jon created some storage conformance tests at https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/UrlSignerV4TestData.json.

Let's keep it consistent in a single place by moving it to this repo. It does not need a generator - we can hand write files, or plaintext specify them in some language (ideally go to be consistent) and minimally generate them.

Additionally, it would be very good for this to be in .proto format.

**Comment by tseaver** [comment]
@jadekler I don't find the proto format a win for specifying the testcases:  it means we have to have extra machinery generated to parse the files (generating for the Firestore `test.proto` is non-trivial), compared to JSON, which all of us can parse natively.  E.g., see the [Bigtable conformance tests](https://github.com/googleapis/google-cloud-python/blob/master/bigtable/tests/unit/read-rows-acceptance-test.json), and how they are [parsed in Python](https://github.com/googleapis/google-cloud-python/blob/58b7c3ba0d302adbd7b9e1511f21e7d29c3a0c3d/bigtable/tests/unit/test_row_data.py#L963-L973).

**Comment by jadekler** [comment]
My 2c: The fact that it's strongly typed makes it much easier (or possible at all, in some cases) in dynamic languages, unfortunately. Multi-language usage wins are the canonical use-case for protos.

(please keep the opinions coming though, happy to discuss further)

**Comment by tseaver** [comment]
In firestore, proto-based test specifications have a little more benefit, since they assert that a given protobuf message is sent to the API (or produce a stream of message responses, in the case of listen).  Unmarshalling them directly from the test specification does reduce the amount of scaffolding each language implementation needs to build.

For V4 signing in storage, there are otherwise no protos in sight:  instead, we have a clear set of "simple" types for the inputs, and a required URL string as the output.

**Comment by jskeet** [comment]
I agree with Tres on the reasons why I chose JSON.  The Firestore conformance tests are more painful to work with, as we need the "text to binary" step for test data. Nothing in Storage C# code uses protos at the moment - it would be odd to introduce them for a less convenient way (than JSON) of providing test data

**Comment by jadekler** [comment]
> The Firestore conformance tests are more painful to work with, as we need the "text to binary" step for test data.

Could you expand on this? What's painful about this - reading .textproto, the code to unmarshal into in-code objects, or something else? I'm probably not grokking the pain y'all are feeling. The former seems natural-ish to me having spent enough time with protos, and the latter is very small amounts of code in Go. (I would totally get it if the latter is quite tedious in other languages)

> Nothing in Storage C# code uses protos at the moment - it would be odd to introduce them [...] rather than JSON

> For V4 signing in storage, there are otherwise no protos in sight

I don't really see these as compelling reasons. Nothing in firestore is doing proto parsing, either. We use protos because:

- It provides strong typing across 7 languages. For our team - which actually has to maintain 7 (soon more?) languages - this is _very valuable_: it helps us avoid subtle mistakes by preventing any human being from having to define types, and subtly getting them wrong
- It provides a specification. Note that in https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/UrlSignerV4TestData.json we are adding comments - this makes that file _not a json file_ and will need to be removed if we were to move it in here, or moved into some string field (JSON does not allow comments). By contrast, protos do allow comments which get turned into nice documentation on the other end. The fact that these get distributed as widely as they do make this centralized documentation a big win
- Strong typing and a specification means that the test structure _strictly_ works for all languages. JSON, on the other hand, can have loosey-goosey typing and work in some languages but not others. For example, the following JSON could be parsed by some dynamically typed languages, but not statically typed languages (the fourth type is unparseable when we only expect an array of `foo int`):
    ```
    [
      {"foo": 5},
      {"foo": 6},
      {"foo": 7},
      {"whoops-this-is-a-mistake": 7}
    ]
    ```

Finally, I am really not keen to support both .json and .proto conformance tests. It would be really nice to have some amount of commonality as we build these things for more services.

--------------

I'm not at all suggesting that we follow firestore's model in any way other than to encode our tests in .proto. To more concretely describe what I'm talking about, here is a rough, untested idea of the .proto I'm describing (translating https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/UrlSignerV4TestData.json):

```
message SignedV4Test {
  required string description = 1;
  required string bucket = 2;
  required string object = 3;
  required string method = 4;
  required int64 expiration = 5;
  required string timestamp = 6;
  required string expectedUrl = 7;
}
```

**Comment by blowmage** [comment]
I would not be opposed to using protobuf to define the test case and data, but we don't use protobuf in storage, and I would rather not add the dependency to run the tests. As long as the data is exported to JSON as well as the binary file I would have no problem.

**Comment by jadekler** [comment]
> As long as the data is exported to JSON as well as the binary file I would have no problem.

Thanks for mentioning, I hadn't thought of that. @jskeet @tseaver WDYT about that approach? It seems to have the advantages of both.

**Comment by frankyn** [comment]
@jadekler IIUC, it'd be a proto binary file generator that also supports a JSON output?

**Comment by jadekler** [comment]
@frankyn I'm not super clued in on how the .binproto thing works, but I'm imagining a .proto specification in which we spit out .json files using something like https://godoc.org/github.com/golang/protobuf/jsonpb.

**Comment by jskeet** [comment]
> Could you expand on this? What's painful about this - reading .textproto, the code to unmarshal into in-code objects, or something else?

The fact that we need to have two representations in source control: the text format and the binary format, because .textproto was chosen instead of JSON. There were reasons for it at the time, but I don't remember them now. It *may* have been the lack of comments in protobuf JSON.

The argument that JSON is more error-prone doesn't apply in the way I'm using them in C# at least - it's effectively equivalent to the proto form, given that I'm converting it to a statically typed class anyway, and everything's validated by the JSON converter. If other languages don't have facilities like that, it would definitely make it harder for those languages to work.

I see there being two top-level choices, and then three "sub-choices" for proto. I'll lay out my positions here.

# Non-proto JSON

Pros:

- Easily parsed everywhere, and understood by pretty much all developers. Someone working on the Storage library currently doesn't need to know anything about protobuf at all, and this option doesn't change that.
- While comments are *strictly* disallowed by JSON specifications, my understanding is that most JSON parsers either allow them by default or can be persuaded to. They're certainly commonly seen.
- Single representation in source control.
- All the data we're interested in for Storage tests can be easily represented in JSON. (That may not be true for other libraries, of course - and I can see the benefit of choosing a single format.)

Cons:

- Not self-describing in the way that protos are.
- *Potentially* error-prone in languages that won't validate in the way that the .NET JSON converter would.

# Proto in some form or other

Pros:

- Clear schema
- When considering *other* APIs, the majority are "proto-native" so requests/responses can be embedded directly
- Reasonably uniform support in all languages

Cons:

- All of the representations have a drawback (see later)
- Increases the burden of understanding for someone looking at just the Storage library
- Headers are relatively painful to represent in protos (see later)

## Proto formats

If we choose to use protos, we need to choose between three formats for what ends up in GitHub:

**Textproto**

- Not supported in all languages, so can't be the only source of truth
- (Subjective) As a Googler with 10 years standing, I still find them really painful to read compared with JSON
- They *do* allow comments

**Binary**

- Not human readable, by definition. Definitely couldn't be the only source of truth.
- Understood by all languages

**JSON**

- Most human readable format
- I *believe* it's supported by all languages
- Does not all comments, so we'd probably want to add a "comment" field in the test

For Firestore, we use "textproto + binary" which means any PR introducing new tests or changing a test has binary file changes along with the more readable ones.
I would definitely prefer to use JSON here. Note that one side-effect of this is that each platform *could* potentially read the tests without even using the protos. (Proto JSON is just regular JSON, after all, with some restrictions.) They'd need to be very careful when adding or modifying tests of course.

## Storage-specific pain point: headers

The "headers" in the current storage tests are effectively a `map<string, repeated string>` - which isn't valid in proto. This is so that in .NET at least, I can test what happens if multiple header values are added. It's possible that other languages don't allow multiple header values to be specified like this anyway, forcing users to do the concatenation... I could potentially live with just a `map<string, string>`, at the cost of adding more unit tests within the C# code.

The current JSON representation is pretty simple:

```json
{
  "headers": {
    "foo": [ "foo-value1", "foo-value2" ],
    "bar": [ "bar-value1", "bar-value2" ]
}
```

However, to represent headers in proto we'd need one of two options:

```proto
// Option 1: a repeated Header message
message SignedV4Test {
  ...
  repeated Header headers = 8;
}

message Header {
  string name = 1;
  repeated string values = 2;
}
```

Sample JSON:

```json
{
  "headers": [
    { "name": "foo", "values": [ "foo-value1", "foo-value2" ] },
    { "name": "bar", "values": [ "bar-value1", "bar-value2" ] },
  ]
}
```

Or:

```proto
// Option 2: a map with a "repeated string" message
message SignedV4Test {
  ...
  map<string, RepeatedString> headers = 8;
}

message RepeatedString {
  repeated string values = 1;
}
```

Sample JSON:

```json
{
  "headers": {
    "foo": { "values": [ "foo-value1", "foo-value2" ] },
    "bar": { "values": [ "bar-value1", "bar-value2" ] },
  }
}
```

Neither of these is as nice (IMO) as the "plain JSON" format. We'd need to weigh up the value of supporting multi-value headers vs the ugliness of test format for this. (We could even have a `map<string, string> simple_headers` which would be good enough for most tests, if we wanted.)

# Jon's recommendation

Personally I'd prefer to stick to "just plain JSON" with a human readable (but not computer verifiable) description at the top of the file. I'd want to confirm that all platforms have JSON parsers that *can* ignore comments though.

If we *do* go with proto, I'd definitely prefer to use JSON as the storage format in GitHub. We'd want to double check that all platforms support that as an input format. If we go with that, we might want to *consider* converting the Firestore tests to JSON as well, and make this the approach for all conformance test data moving forward.

# Note on GitHub organization

I seem to remember that when a similar issue was brought up in the past, some contributors disliked using google-cloud-common for this. @JustinBeckwith could you comment on that part?

**Comment by blowmage** [comment]
> The "headers" in the current storage tests are effectively a `map<string, repeated string>`

What about using a `struct`? That would allow for a header value to be both a string and a list of strings, wouldn’t it?

**Comment by jskeet** [comment]
> What about using a `struct`?

Yes, but that means we lose the validation which is half the point of using protos :)

**Comment by jadekler** [comment]
Thanks for the weigh-in, Jon. I greatly appreciated reading through your thinking. I think my choice would be .proto specified .json, but I'll defer to y'all.

> The "headers" in the current storage tests are effectively a map<string, repeated string> - which isn't valid in proto. 

You're right, this is a bummer. I've run into it once before and it sucked then as much as it does now.

**Comment by jadekler** [comment]
Btw, to help the discussion, I've created a PoC of storage integration tests using a .proto specification that outputs .json testcases: https://github.com/googleapis/google-cloud-common/pull/282

Note that it is _significantly_ lighter weight than firestore. :)

**Comment by jadekler** [comment]
Closing this: we've decided to create a new repo.
